server:
  port: 8080
# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /anon

spring:
  application:
    name: springboot-security
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: '${spring.application.name}::'
      cache-null-values: false #是否缓存空值
      time-to-live: 1h #缓存超时时间ms
# redis 配置
  redis:
    # 默认16个分片
    database: 0
    host: redis-18419.c259.us-central1-2.gce.cloud.redislabs.com
    port: 18419
    password: eJwEgP1ufA81If7BYirHysAqZako3kxZ
    timeout: 10000

mybatis-plus:
#  mapper.xml扫描路径
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
#    数据库下划线转驼峰命名映射
    map-underscore-to-camel-case: true
#    自动映射列到字段或属性
    auto-mapping-behavior: full
#    sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      配置逻辑删除字段为1是删除
      logic-not-delete-value: 1
#      配置逻辑删除字段为0是未删除
      logic-delete-value: 0

logging:
  config: classpath:logback-spring.xml

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟，设置为1周过期）
  expireTime: 10000
